tienda/tienda/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('watson.urls')),
    # path('api-auth/', include('rest_framework.urls')),
    path('api/rest/', include('watson.api.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/watson/api/urls.py
from django.urls import path, include

from watson.api.chatbot.api import ChatsmsView


urlpatterns=[
    path("chatbot/",ChatsmsView.as_view()),
]

tienda/watson/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('login/', views.login, name='login'),
    path('new', views.new, name='nuevo'),
    path('entrenar', views.entrenar, name='entrenar'),
    path('ajax/productos/', views.cargarProduct, name ='ajax_cargarProduct')
]

tienda/watson/models.py
from django.db import models
from django.contrib.auth.models import User



class Frecuencia(models.Model):
    frecuencia = models.CharField(max_length=200)


class PerfilUsuario(models.Model):
    fecha_nacimiento = models.DateTimeField()
    frecuencia = models.ForeignKey(Frecuencia, on_delete=models.PROTECT, null=True)
    sexo = models.ForeignKey('Sexo', on_delete=models.PROTECT, null=True)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    anot = models.IntegerField(null=True)


class Producto(models.Model):
    producto = models.CharField(max_length=200)
    img_producto = models.ImageField(upload_to="producto", max_length=200, null=True, blank=True)

    def __str__(self) -> str:
        return self.producto


class Sexo(models.Model):
    sexo = models.CharField(max_length=20)


class UsuarioProducto(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT, null=True)

tienda/watson/forms.py
from django import forms
from .models import Producto, Sexo
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomChoiceField(forms.ModelChoiceField):

    def label_from_instance(self, obj):
        print(obj)
        return mark_safe("<img src="'%s' % obj.img_producto.url)


class ChattForm(forms.Form):
    mensaje = forms.CharField(required=False)


BIRTH_YEAR_CHOICES = range(1980, 2020)


class UsuarioForm(UserCreationForm):
    usuario = forms.CharField(max_length=30, required=True)
    nombres = forms.CharField(max_length=30, required=True)
    apellidos = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('usuario', 'nombres', 'apellidos', 'email', 'password1',
                  'password2')

class ProfileForm(forms.Form):
    sexo = forms.ChoiceField(choices=[(1, 'Masculino'), (2, 'Femenino')])
    fecha_nacimiento = forms.DateField(widget=forms.SelectDateWidget(years=BIRTH_YEAR_CHOICES))

class ProductoForm(forms.Form):
    producto = forms.ModelMultipleChoiceField(queryset=Producto.objects.all(),
                                              required=True,
                                              widget=forms.CheckboxSelectMultiple())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['producto'].queryset = Producto.objects.all()
        if 'producto' in self.data:
            try:
                idPro = [int(i) for i in dict(self.data)['producto']]
                self.fields['producto'].queryset = Producto.objects.filter(id__in=idPro)
            except (ValueError, TypeError):
                pass


class EntrenarForm(forms.Form):
    vecino = forms.IntegerField()

tienda/watson/views.py
import random
import pandas as pd
import datetime
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as dj_login
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import ChattForm, UsuarioForm, EntrenarForm, ProfileForm, ProductoForm
from joblib import load
from .models import Sexo, Frecuencia, Producto, PerfilUsuario, UsuarioProducto
from django.contrib.auth.models import User
from .modulo.chat.asistente import asistente
from .modulo.knn.preProcesamiento.matrizCompra import cambioData
from .modulo.knn.entrenamiento.entrenar import entrenarM
from .modulo.knn.preProcesamiento.dataLista import matrizCom, producto


def index(request):
    sms=''
    intento=''
    respuesta=''
    nuevo = []
    pr = []
    if request.user.is_authenticated:
        # cuando el usuario este logeado obtendra su id de bd
        idUser = request.user.id
        idProduct = list(UsuarioProducto.objects.filter(usuario=idUser).values('producto__id'))
        for i in range(0,len(idProduct)):
            nuevo.append(idProduct[i]['producto__id'])
    if request.method == "POST":
        try:
            form = ChattForm(request.POST)
            if form.is_valid():
                sms = form.cleaned_data['mensaje']
                intento, respuesta = asistente(sms)
                # condicion recomendador
                if intento=='recomendar':
                    pr = "hola"
                    product=" ".join(producto(random.choice(nuevo)))
        except Exception as e:
            print(e)
    else:
        form = ChattForm()
    return render(request, 'watson/index2.html',{'form':form, 'sms':sms,'intent': intento, 'resp':respuesta
                  ,'recomen':pr})

def new(request):
    if request.method=='POST':
        form = UsuarioForm(request.POST)
        form1 = ProfileForm(request.POST)
        form2 = ProductoForm(request.POST)
        if form.is_valid() and form1.is_valid() and form2.is_valid():
            nombre = form.cleaned_data.get('nombres')
            apellido = form.cleaned_data.get('apellidos')
            contrasena = form.cleaned_data.get('password1')
            usuario = form.cleaned_data.get('usuario')
            email = form.cleaned_data.get('email')
            fecha_nacimiento= form1.cleaned_data.get('fecha_nacimiento')
            sexo = form1.cleaned_data.get('sexo')
            # retorna solo los productos que seleccionen
            productos = form2.cleaned_data.get('producto')
            ltId = list(productos.values('id'))
            user = User(username=usuario, first_name=nombre, last_name=apellido, email=email,
                                            date_joined=datetime.datetime.now(), is_superuser=False,
                                            is_staff=True, is_active=True)
            user.set_password(contrasena)
            user.save()
            sex = Sexo.objects.get(id=sexo)
            frec = Frecuencia.objects.get(id=1)
            aaa = User.objects.get(username=nombre, first_name=nombre, last_name=apellido, email=email)
            p = PerfilUsuario(fecha_nacimiento=fecha_nacimiento, frecuencia=frec, sexo=sex,usuario=aaa)
            p.save()
            # ciclo para asignar usuario producto
            for i in range(0,len(ltId)):
                # consultar productos
                produ = Producto.objects.get(id=ltId[i]['id'])
                # asignar usuario producto
                pro = UsuarioProducto(usuario=aaa, producto=produ)
                # almacenar en bd
                pro.save()
            # redireccionar a la pagina login
            return redirect('login')
    else:
        form = UsuarioForm()
        form1 = ProfileForm()
        form2 = ProductoForm()
    return render(request, 'watson/new.html', {'form': form,'form1': form1,'form2': form2})

def login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            dj_login(request, user)
            return redirect('index')
        else:
            messages.info(request,'Usuario o contraseña incorrecta')
    return render(request, 'watson/login.html')

def entrenar(request):
    # lista para guardar los datos de cursos y estudiante
    accuracy = 0
    recall = 0
    precision = 0
    datos=[]
    if request.method == "POST":
        try:
            csv_file = request.FILES["csv_file"]
            # verificar si es un archivo csv
            data_set = csv_file.read().decode('UTF-8')
            # obtener lineas del csv
            data = (data_set.split('\n'))
            # obtener nombre de las columnas
            colums = data[0].split(';')
            co = [i.replace('\r', '') for i in colums]
            # de las lineas convertir en una lista
            for i in range(1,len(data)):
                tam = len(data[i].split(';'))
                # verificar tamaño de la lista
                if tam == len(colums):
                    # todas las listas de datos se agrega nueva lista
                    dt = data[i].split(';')
                    datos.append([i.replace('\r', '') for i in dt])
            # creando dataframe
            df = pd.DataFrame(datos,columns=co)
            form = EntrenarForm(request.POST)
            if form.is_valid():
                vecino = form.cleaned_data.get('vecino')
                # generando matriz de compra
                m = cambioData(df)
                # data preparada
                dat = matrizCom(m)
                accuracy, precision, recall = entrenarM(dat,vecino)
        except Exception as e:
            print(e)
    else:
         form=EntrenarForm()

    return render(request, 'watson/entrenar.html',{'form':form,'accuracy': accuracy, 'recall': recall,
                   'precision': precision})

def cargarProduct(request):
    idPro=[]
    # obtnemos el sexo y el año de nacimiento por el ajax
    id_sex = request.GET.get("sexo")
    anio = request.GET.get("edad")
    # control de varibles
    if anio is None:
        edad = 18
    else:
        # calcular edad del usuario
        edad = 2020 - int(anio)
    # asingnar id del sexo usuario
    if id_sex is None:
        id_sexo = 1
    else:
        id_sexo = int(id_sex)
    # cargando modelo preentrenado
    clf = load('recom.joblib')
    # lista de productos
    pro = ['Comida para bebés', 'Pañales', 'Fórmula', 'Loción', 'Jabón para bebés', 'Toallitas húmedas', 'Frutas frescas',
                'Verduras frescas', 'Cerveza', 'Vino', 'Club Soda', 'Bebida deportiva',
                'Patatas fritas', 'Palomitas de maíz', 'Harina de avena', 'Medicamentos', 'Alimentos enlatados', 'Cigarrillos', 'Queso',
                'Productos de limpieza', 'Condimentos', 'Alimentos congelados', 'Artículos de cocina', 'Carne',
                'Suministros de oficina', 'Cuidado personal', 'Suministros para mascotas']
    # ciclo para recorrer los productos
    for idProducto in range(0, len(pro)):
        # predecir si el producto es ideal para el usuario
        pred = clf.predict([[idProducto, id_sexo, edad, 1]])
            # print(idProducto,'-',idGenero,'-',edad,'-',idEstado)
            # condicion para que imprima las recomendaciones basado en datos
            # del usuario como genero, edad, estado
        # almacena solo los productos que son para el usuario en base al modelo buscando en la base de datos
        # para obtener el id de registro
        if pred[0] > 0:
            idPro.append(list(Producto.objects.filter(
                    producto__icontains=pro[idProducto]).values('id'))[0]['id'])
    # el modelo no predice 10 producto por lo cual
    # generamos una lista de id de productos aleatorios para que se presente los productos faltantes
    # y completar los productos
    aux = random.sample(range(2,20),10-len(idPro))
    # si el modelo predice algunos productos actualiza su lista con la lista de aleatorios
    idPro.extend(aux)
    # realizamos una consulta a la base de datos con la lista de id de productos generado
    valor = Producto.objects.filter(id__in=idPro)
    return render(request, 'watson/form_list_product.html', {'productos': valor})

tienda/watson/templates/watson/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    {% block moreHead %}
    {% endblock %}
</head>

{% block moreBody %}
{% endblock %}
<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
{% block JSS %}
{% endblock %}
</body>
</html>

tienda/watson/templates/watson/entrenar.html
{% extends 'watson/base.html' %}
{% block moreBody %}
<body class="bg-gradient-primary">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <h2 class="text-center">ENTRENAR MODELO KNN</h2>
                    <div class="card shadow">
                        <div class="container">
                            <div class="row">
                                <div class="col">
                                    <form action="{% url 'entrenar'  %}" method="POST" enctype="multipart/form-data"
                                          class="form-horizontal">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for='name'
                                                   class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
                                            <div class="col-md-8">
                                                <input type="file" name="csv_file" id="csv_file" required="True"
                                                       class="form-control">
                                            </div>
                                            <div class="col-md-auto">
                                                {{ form }}
                                            </div>
                                        </div>
                                        <button class="btn btn-primary"><span class="glyphicon glyphicon-upload"
                                                                              style="margin-right:5px;"></span>Entrenar
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <div class="card shadow mb-4">
                                <h2 align="center" style="color: #2d4373; "><b>RESULTADOS</b></h2>
                                <style>
                                    #chartdiv {
                                        width: 100%;
                                        height: 500px;
                                    }
                                </style>
                                <div id="chartdiv"></div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}
{% block JSS %}
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<script>
    am4core.ready(function () {
        am4core.useTheme(am4themes_animated);
        var chart = am4core.create('chartdiv', am4charts.XYChart)
        chart.colors.step = 2;
        chart.legend = new am4charts.Legend()
        chart.legend.position = 'top'
        chart.legend.paddingBottom = 20
        chart.legend.labels.template.maxWidth = 95
        var xAxis = chart.xAxes.push(new am4charts.CategoryAxis())
        xAxis.dataFields.category = 'category'
        xAxis.renderer.cellStartLocation = 0.1
        xAxis.renderer.cellEndLocation = 0.9
        xAxis.renderer.grid.template.location = 0;
        var yAxis = chart.yAxes.push(new am4charts.ValueAxis());
        yAxis.min = 0;

        function createSeries(value, name) {
            var series = chart.series.push(new am4charts.ColumnSeries())
            series.dataFields.valueY = value
            series.dataFields.categoryX = 'category'
            series.name = name
            series.events.on("hidden", arrangeColumns);
            series.events.on("shown", arrangeColumns);
            var bullet = series.bullets.push(new am4charts.LabelBullet())
            bullet.interactionsEnabled = false
            bullet.dy = 30;
            bullet.label.text = '{valueY}'
            bullet.label.fill = am4core.color('#ffffff')
            return series;
        }

        chart.data = [{
            category: 'Metricas',
            first: {{accuracy | safe}},
            second: {{recall | safe}},
            third: {{precision | safe}}
        }]
        createSeries('first', 'accuracy');
        createSeries('second', 'recall');
        createSeries('third', 'precision');

        function arrangeColumns() {
            var series = chart.series.getIndex(0);
            var w = 1 - xAxis.renderer.cellStartLocation - (1 - xAxis.renderer.cellEndLocation);
            if (series.dataItems.length > 1) {
                var x0 = xAxis.getX(series.dataItems.getIndex(0), "categoryX");
                var x1 = xAxis.getX(series.dataItems.getIndex(1), "categoryX");
                var delta = ((x1 - x0) / chart.series.length) * w;
                if (am4core.isNumber(delta)) {
                    var middle = chart.series.length / 2;
                    var newIndex = 0;
                    chart.series.each(function (series) {
                        if (!series.isHidden && !series.isHiding) {
                            series.dummyData = newIndex;
                            newIndex++;
                        }
                        else {
                            series.dummyData = chart.series.indexOf(series);
                        }
                    })
                    var visibleCount = newIndex;
                    var newMiddle = visibleCount / 2;
                    chart.series.each(function (series) {
                        var trueIndex = chart.series.indexOf(series);
                        var newIndex = series.dummyData;
                        var dx = (newIndex - trueIndex + middle - newMiddle) * delta
                        series.animate({
                            property: "dx",
                            to: dx
                        }, series.interpolationDuration, series.interpolationEasing);
                        series.bulletsContainer.animate({
                            property: "dx",
                            to: dx
                        }, series.interpolationDuration, series.interpolationEasing);
                    })
                }
            }
        }
    }); // end am4core.ready()
</script>
{% endblock %}

tienda/watson/templates/watson/form_list_product.html
<!-- ciclo for para recorrer los productos consultados creando un formulario dinamico -->
{% for product in productos %}
<li>
    <label for="id_producto_{{ product.id }}">
        <input type="checkbox" name="producto" value="{{ product.id }}" id="id_producto_{{ product.id }}">
            {{ product.producto }}
    </label>
</li>
{% endfor %}

tienda/watson/templates/watson/login.html
{% extends 'watson/base.html' %}
{% block moreBody %}
<body class="bg-gradient-primary">
<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Bienvenido</h1>
                                </div>
                                <form class="user" method="POST" action="">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" name="username" class="form-control form-control-user"
                                               id="exampleInputEmail" aria-describedby="emailHelp"
                                               placeholder="Ingrese su usuario...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control form-control-user"
                                               id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-user btn-block">Login</button>

                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'nuevo'%}">Crear una cuenta!</a>
                                </div>
                                {% for message in messages %}
                                <p id="messages">{{ message }}</p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

tienda/watson/templates/watson/new.html
{% extends 'watson/base.html' %}
{% block moreBody %}
<body class="bg-gradient-primary">
<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Gracias Por Preferirnos</h1>
                            </div>
                            <form method="POST" id="userForm" data-produc-url="{% url 'ajax_cargarProduct' %}" novalidate>
                                {% csrf_token %}
                                <div class="container">
                                    <table>
                                        {{form}}
                                        {{form1}}
                                        {{form2}}
                                        {{field.errors}}
                                    </table>
                                    <button class="btn btn-primary" data-toggle="modal"
                                            data-target="#exampleModal"><span
                                            class="glyphicon glyphicon-upload"
                                            style="margin-right:5px;"></span>Crear cuenta
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}
{% block JSS %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $('#id_sexo, #id_fecha_nacimiento_year').change(function () {
        const url = $('#userForm').attr("data-produc-url");
        var sexo = $('#id_sexo').val();
        var edad = $('#id_fecha_nacimiento_year').val();
        $.ajax({
            url: url,
            data: {"sexo": sexo,"edad": edad},
            success: function (data) {
                console.log(data);
                $("#id_producto").html(data);}
        });
    });
</script>
{% endblock %}